const topics = ["Greetings", "Family", "Numbers", "Colors", "Daily routine", "Animals", "Weather", "Food"];

const bank = {
  "Greetings": [
    { t: "How do you say 'Hola' in English?", o: ["Hello", "Goodbye", "Please", "Thanks"], c: 0, e: "Hello = Hola." },
    { t: "How do you say 'Adios' in English?", o: ["Goodbye", "Hello", "Please", "Thanks"], c: 0, e: "Goodbye = Adios." },
    { t: "How do you say 'Por favor' in English?", o: ["Please", "Thanks", "Hello", "Goodbye"], c: 0, e: "Please = Por favor." },
    { t: "How do you say 'Gracias' in English?", o: ["Thanks", "Please", "Hello", "Goodbye"], c: 0, e: "Thanks = Gracias." },
    { t: "How do you say 'Buenos dias' in English?", o: ["Good morning", "Good night", "Good afternoon", "Goodbye"], c: 0, e: "Good morning = Buenos dias." },
    { t: "How do you say 'Buenas noches' in English?", o: ["Good night", "Good morning", "Good afternoon", "Hello"], c: 0, e: "Good night = Buenas noches." },
    { t: "How do you say 'Como estas?' in English?", o: ["How are you?", "What is your name?", "How old are you?", "Where are you?"], c: 0, e: "How are you? = Como estas?" },
    { t: "How do you say 'Me llamo...' in English?", o: ["My name is...", "I am...", "I have...", "I like..."], c: 0, e: "My name is... = Me llamo..." },
    { t: "What does 'Nice to meet you' mean?", o: ["Encantado de conocerte", "Como estas", "Adios", "Gracias"], c: 0, e: "Nice to meet you = Encantado de conocerte." },
    { t: "What does 'See you later' mean?", o: ["Hasta luego", "Buenos dias", "Gracias", "Por favor"], c: 0, e: "See you later = Hasta luego." },
    { t: "What does 'How old are you?' mean?", o: ["Cuantos años tienes?", "Como estas?", "Donde vives?", "Que haces?"], c: 0, e: "How old are you? = Cuantos años tienes?" },
    { t: "What does 'Where are you from?' mean?", o: ["De donde eres?", "Como estas?", "Que haces?", "Cuantos años tienes?"], c: 0, e: "Where are you from? = De donde eres?" },
    { t: "What does 'What is your name?' mean?", o: ["Como te llamas?", "Cuantos años tienes?", "De donde eres?", "Como estas?"], c: 0, e: "What is your name? = Como te llamas?" },
    { t: "What does 'Good afternoon' mean?", o: ["Buenas tardes", "Buenos dias", "Buenas noches", "Adios"], c: 0, e: "Good afternoon = Buenas tardes." },
    { t: "How do you say 'Lo siento' in English?", o: ["I'm sorry", "Excuse me", "Please", "Thanks"], c: 0, e: "I'm sorry = Lo siento." },
    { t: "How do you say 'Disculpe' in English?", o: ["Excuse me", "I'm sorry", "Please", "Thanks"], c: 0, e: "Excuse me = Disculpe." },
    { t: "What does 'You're welcome' mean?", o: ["De nada", "Gracias", "Por favor", "Adios"], c: 0, e: "You're welcome = De nada." },
    { t: "What does 'Take care' mean?", o: ["Cuidate", "Adios", "Hola", "Gracias"], c: 0, e: "Take care = Cuidate." },
    { t: "How do you say 'Feliz cumpleaños' in English?", o: ["Happy birthday", "Merry Christmas", "Happy new year", "Goodbye"], c: 0, e: "Happy birthday = Feliz cumpleaños." },
    { t: "What does 'Merry Christmas' mean?", o: ["Feliz Navidad", "Feliz cumpleaños", "Feliz año nuevo", "Adios"], c: 0, e: "Merry Christmas = Feliz Navidad." }
  ],
  "Family": [
    { t: "How do you say 'Madre' in English?", o: ["Mother", "Father", "Sister", "Brother"], c: 0, e: "Mother = Madre." },
    { t: "How do you say 'Padre' in English?", o: ["Father", "Mother", "Sister", "Brother"], c: 0, e: "Father = Padre." },
    { t: "How do you say 'Hermana' in English?", o: ["Sister", "Brother", "Mother", "Father"], c: 0, e: "Sister = Hermana." },
    { t: "How do you say 'Hermano' in English?", o: ["Brother", "Sister", "Mother", "Father"], c: 0, e: "Brother = Hermano." },
    { t: "How do you say 'Abuelo' in English?", o: ["Grandfather", "Grandmother", "Uncle", "Aunt"], c: 0, e: "Grandfather = Abuelo." },
    { t: "How do you say 'Abuela' in English?", o: ["Grandmother", "Grandfather", "Uncle", "Aunt"], c: 0, e: "Grandmother = Abuela." },
    { t: "How do you say 'Tio' in English?", o: ["Uncle", "Aunt", "Cousin", "Nephew"], c: 0, e: "Uncle = Tio." },
    { t: "How do you say 'Tia' in English?", o: ["Aunt", "Uncle", "Cousin", "Niece"], c: 0, e: "Aunt = Tia." },
    { t: "How do you say 'Primo' in English?", o: ["Cousin", "Nephew", "Niece", "Brother"], c: 0, e: "Cousin = Primo." },
    { t: "How do you say 'Sobrino' in English?", o: ["Nephew", "Niece", "Cousin", "Brother"], c: 0, e: "Nephew = Sobrino." },
    { t: "How do you say 'Sobrina' in English?", o: ["Niece", "Nephew", "Cousin", "Sister"], c: 0, e: "Niece = Sobrina." },
    { t: "How do you say 'Esposo' in English?", o: ["Husband", "Wife", "Son", "Daughter"], c: 0, e: "Husband = Esposo." },
    { t: "How do you say 'Esposa' in English?", o: ["Wife", "Husband", "Daughter", "Son"], c: 0, e: "Wife = Esposa." },
    { t: "How do you say 'Hijo' in English?", o: ["Son", "Daughter", "Brother", "Sister"], c: 0, e: "Son = Hijo." },
    { t: "How do you say 'Hija' in English?", o: ["Daughter", "Son", "Sister", "Brother"], c: 0, e: "Daughter = Hija." },
    { t: "What does 'Family' mean?", o: ["Familia", "Amigos", "Vecinos", "Compañeros"], c: 0, e: "Family = Familia." },
    { t: "What does 'Parents' mean?", o: ["Padres", "Hermanos", "Abuelos", "Tios"], c: 0, e: "Parents = Padres." },
    { t: "What does 'Children' mean?", o: ["Hijos", "Padres", "Abuelos", "Tios"], c: 0, e: "Children = Hijos." },
    { t: "What does 'Baby' mean?", o: ["Bebe", "Niño", "Adulto", "Anciano"], c: 0, e: "Baby = Bebe." },
    { t: "What does 'Twins' mean?", o: ["Gemelos", "Hermanos", "Primos", "Amigos"], c: 0, e: "Twins = Gemelos." }
  ],
  "Numbers": [
    { t: "How do you say '1' in English?", o: ["One", "Two", "Three", "Four"], c: 0, e: "One = 1." },
    { t: "How do you say '2' in English?", o: ["Two", "One", "Three", "Four"], c: 0, e: "Two = 2." },
    { t: "How do you say '3' in English?", o: ["Three", "Two", "Four", "Five"], c: 0, e: "Three = 3." },
    { t: "How do you say '4' in English?", o: ["Four", "Three", "Five", "Six"], c: 0, e: "Four = 4." },
    { t: "How do you say '5' in English?", o: ["Five", "Four", "Six", "Seven"], c: 0, e: "Five = 5." },
    { t: "How do you say '10' in English?", o: ["Ten", "Eleven", "Twelve", "Nine"], c: 0, e: "Ten = 10." },
    { t: "How do you say '20' in English?", o: ["Twenty", "Thirty", "Forty", "Ten"], c: 0, e: "Twenty = 20." },
    { t: "How do you say '100' in English?", o: ["One hundred", "One thousand", "Ten", "Twenty"], c: 0, e: "One hundred = 100." },
    { t: "How do you say '1000' in English?", o: ["One thousand", "One hundred", "Ten thousand", "One million"], c: 0, e: "One thousand = 1000." },
    { t: "What does 'First' mean?", o: ["Primero", "Segundo", "Tercero", "Cuarto"], c: 0, e: "First = Primero." },
    { t: "What does 'Second' mean?", o: ["Segundo", "Primero", "Tercero", "Cuarto"], c: 0, e: "Second = Segundo." },
    { t: "What does 'Third' mean?", o: ["Tercero", "Primero", "Segundo", "Cuarto"], c: 0, e: "Third = Tercero." },
    { t: "What does 'Half' mean?", o: ["Mitad", "Tercio", "Cuarto", "Quinto"], c: 0, e: "Half = Mitad." },
    { t: "What does 'Quarter' mean?", o: ["Cuarto", "Mitad", "Tercio", "Octavo"], c: 0, e: "Quarter = Cuarto." },
    { t: "What does 'Zero' mean?", o: ["Cero", "Uno", "Dos", "Tres"], c: 0, e: "Zero = Cero." },
    { t: "How do you say '6' in English?", o: ["Six", "Seven", "Eight", "Five"], c: 0, e: "Six = 6." },
    { t: "How do you say '7' in English?", o: ["Seven", "Six", "Eight", "Nine"], c: 0, e: "Seven = 7." },
    { t: "How do you say '8' in English?", o: ["Eight", "Seven", "Nine", "Ten"], c: 0, e: "Eight = 8." },
    { t: "How do you say '9' in English?", o: ["Nine", "Eight", "Ten", "Seven"], c: 0, e: "Nine = 9." },
    { t: "How do you say '11' in English?", o: ["Eleven", "Twelve", "Thirteen", "Ten"], c: 0, e: "Eleven = 11." }
  ],
  "Colors": [
    { t: "How do you say 'Rojo' in English?", o: ["Red", "Blue", "Green", "Yellow"], c: 0, e: "Red = Rojo." },
    { t: "How do you say 'Azul' in English?", o: ["Blue", "Red", "Green", "Yellow"], c: 0, e: "Blue = Azul." },
    { t: "How do you say 'Verde' in English?", o: ["Green", "Red", "Blue", "Yellow"], c: 0, e: "Green = Verde." },
    { t: "How do you say 'Amarillo' in English?", o: ["Yellow", "Red", "Blue", "Green"], c: 0, e: "Yellow = Amarillo." },
    { t: "How do you say 'Negro' in English?", o: ["Black", "White", "Brown", "Gray"], c: 0, e: "Black = Negro." },
    { t: "How do you say 'Blanco' in English?", o: ["White", "Black", "Brown", "Gray"], c: 0, e: "White = Blanco." },
    { t: "How do you say 'Naranja' in English?", o: ["Orange", "Red", "Yellow", "Pink"], c: 0, e: "Orange = Naranja." },
    { t: "How do you say 'Morado' in English?", o: ["Purple", "Blue", "Pink", "Red"], c: 0, e: "Purple = Morado." },
    { t: "How do you say 'Rosa' in English?", o: ["Pink", "Purple", "Red", "Orange"], c: 0, e: "Pink = Rosa." },
    { t: "How do you say 'Marron' in English?", o: ["Brown", "Black", "Gray", "Red"], c: 0, e: "Brown = Marron." },
    { t: "How do you say 'Gris' in English?", o: ["Gray", "Black", "White", "Brown"], c: 0, e: "Gray = Gris." },
    { t: "How do you say 'Dorado' in English?", o: ["Golden", "Silver", "Copper", "Bronze"], c: 0, e: "Golden = Dorado." },
    { t: "How do you say 'Plateado' in English?", o: ["Silver", "Golden", "Copper", "Bronze"], c: 0, e: "Silver = Plateado." },
    { t: "How do you say 'Celeste' in English?", o: ["Light blue", "Dark blue", "Navy", "Blue"], c: 0, e: "Light blue = Celeste." },
    { t: "How do you say 'Beige' in English?", o: ["Beige", "Brown", "Tan", "Cream"], c: 0, e: "Beige = Beige." },
    { t: "What does 'Color' mean?", o: ["Color", "Paint", "Shade", "Hue"], c: 0, e: "Color = Color." },
    { t: "What does 'Rainbow' mean?", o: ["Arcoiris", "Lluvia", "Nube", "Sol"], c: 0, e: "Rainbow = Arcoiris." },
    { t: "What does 'Dark' mean?", o: ["Oscuro", "Claro", "Brillante", "Suave"], c: 0, e: "Dark = Oscuro." },
    { t: "What does 'Light' mean?", o: ["Claro", "Oscuro", "Brillante", "Suave"], c: 0, e: "Light = Claro." },
    { t: "What does 'Bright' mean?", o: ["Brillante", "Oscuro", "Claro", "Suave"], c: 0, e: "Bright = Brillante." }
  ],
  "Daily routine": [
    { t: "How do you say 'Despertarse' in English?", o: ["Wake up", "Sleep", "Eat", "Run"], c: 0, e: "Wake up = Despertarse." },
    { t: "How do you say 'Ducharse' in English?", o: ["Take a shower", "Brush teeth", "Comb hair", "Wash hands"], c: 0, e: "Take a shower = Ducharse." },
    { t: "How do you say 'Cepillarse los dientes' in English?", o: ["Brush teeth", "Wash face", "Comb hair", "Shave"], c: 0, e: "Brush teeth = Cepillarse los dientes." },
    { t: "How do you say 'Desayunar' in English?", o: ["Have breakfast", "Have lunch", "Have dinner", "Snack"], c: 0, e: "Have breakfast = Desayunar." },
    { t: "How do you say 'Almorzar' in English?", o: ["Have lunch", "Have breakfast", "Have dinner", "Snack"], c: 0, e: "Have lunch = Almorzar." },
    { t: "How do you say 'Cenar' in English?", o: ["Have dinner", "Have breakfast", "Have lunch", "Snack"], c: 0, e: "Have dinner = Cenar." },
    { t: "How do you say 'Ir a la escuela' in English?", o: ["Go to school", "Go to work", "Go home", "Go to bed"], c: 0, e: "Go to school = Ir a la escuela." },
    { t: "How do you say 'Dormir' in English?", o: ["Sleep", "Wake up", "Eat", "Run"], c: 0, e: "Sleep = Dormir." },
    { t: "How do you say 'Estudiar' in English?", o: ["Study", "Play", "Eat", "Sleep"], c: 0, e: "Study = Estudiar." },
    { t: "How do you say 'Jugar' in English?", o: ["Play", "Study", "Eat", "Sleep"], c: 0, e: "Play = Jugar." },
    { t: "How do you say 'Comer' in English?", o: ["Eat", "Drink", "Sleep", "Run"], c: 0, e: "Eat = Comer." },
    { t: "How do you say 'Beber' in English?", o: ["Drink", "Eat", "Sleep", "Run"], c: 0, e: "Drink = Beber." },
    { t: "How do you say 'Caminar' in English?", o: ["Walk", "Run", "Jump", "Sit"], c: 0, e: "Walk = Caminar." },
    { t: "How do you say 'Correr' in English?", o: ["Run", "Walk", "Jump", "Sit"], c: 0, e: "Run = Correr." },
    { t: "How do you say 'Leer' in English?", o: ["Read", "Write", "Draw", "Sing"], c: 0, e: "Read = Leer." },
    { t: "How do you say 'Escribir' in English?", o: ["Write", "Read", "Draw", "Sing"], c: 0, e: "Write = Escribir." },
    { t: "How do you say 'Dibujar' in English?", o: ["Draw", "Write", "Read", "Sing"], c: 0, e: "Draw = Dibujar." },
    { t: "How do you say 'Cantar' in English?", o: ["Sing", "Dance", "Play", "Read"], c: 0, e: "Sing = Cantar." },
    { t: "How do you say 'Bailar' in English?", o: ["Dance", "Sing", "Play", "Read"], c: 0, e: "Dance = Bailar." },
    { t: "How do you say 'Salir' in English?", o: ["Go out", "Come in", "Stay", "Sleep"], c: 0, e: "Go out = Salir." }
  ],
  "Animals": [
    { t: "How do you say 'Perro' in English?", o: ["Dog", "Cat", "Bird", "Fish"], c: 0, e: "Dog = Perro." },
    { t: "How do you say 'Gato' in English?", o: ["Cat", "Dog", "Bird", "Fish"], c: 0, e: "Cat = Gato." },
    { t: "How do you say 'Pajaro' in English?", o: ["Bird", "Dog", "Cat", "Fish"], c: 0, e: "Bird = Pajaro." },
    { t: "How do you say 'Pez' in English?", o: ["Fish", "Dog", "Cat", "Bird"], c: 0, e: "Fish = Pez." },
    { t: "How do you say 'Caballo' in English?", o: ["Horse", "Cow", "Sheep", "Pig"], c: 0, e: "Horse = Caballo." },
    { t: "How do you say 'Vaca' in English?", o: ["Cow", "Horse", "Sheep", "Pig"], c: 0, e: "Cow = Vaca." },
    { t: "How do you say 'Conejo' in English?", o: ["Rabbit", "Mouse", "Cat", "Dog"], c: 0, e: "Rabbit = Conejo." },
    { t: "How do you say 'Raton' in English?", o: ["Mouse", "Rabbit", "Cat", "Dog"], c: 0, e: "Mouse = Raton." },
    { t: "How do you say 'Turtle' in English?", o: ["Tortuga", "Serpiente", "Rana", "Pez"], c: 0, e: "Turtle = Tortuga." },
    { t: "How do you say 'Serpiente' in English?", o: ["Snake", "Lizard", "Frog", "Fish"], c: 0, e: "Snake = Serpiente." },
    { t: "How do you say 'Rana' in English?", o: ["Frog", "Snake", "Lizard", "Fish"], c: 0, e: "Frog = Rana." },
    { t: "How do you say 'León' in English?", o: ["Lion", "Tiger", "Bear", "Wolf"], c: 0, e: "Lion = Leon." },
    { t: "How do you say 'Tigre' in English?", o: ["Tiger", "Lion", "Bear", "Wolf"], c: 0, e: "Tiger = Tigre." },
    { t: "How do you say 'Oso' in English?", o: ["Bear", "Lion", "Tiger", "Wolf"], c: 0, e: "Bear = Oso." },
    { t: "How do you say 'Elefante' in English?", o: ["Elephant", "Giraffe", "Rhino", "Hippo"], c: 0, e: "Elephant = Elefante." },
    { t: "How do you say 'Jirafa' in English?", o: ["Giraffe", "Elephant", "Rhino", "Hippo"], c: 0, e: "Giraffe = Jirafa." },
    { t: "How do you say 'Mono' in English?", o: ["Monkey", "Gorilla", "Chimp", "Lemur"], c: 0, e: "Monkey = Mono." },
    { t: "How do you say 'Ballena' in English?", o: ["Whale", "Dolphin", "Shark", "Seal"], c: 0, e: "Whale = Ballena." },
    { t: "How do you say 'Delfin' in English?", o: ["Dolphin", "Whale", "Shark", "Seal"], c: 0, e: "Dolphin = Delfin." },
    { t: "How do you say 'Pato' in English?", o: ["Duck", "Goose", "Swan", "Chicken"], c: 0, e: "Duck = Pato." }
  ],
  "Weather": [
    { t: "How do you say 'Lluvia' in English?", o: ["Rain", "Snow", "Wind", "Sun"], c: 0, e: "Rain = Lluvia." },
    { t: "How do you say 'Nieve' in English?", o: ["Snow", "Rain", "Wind", "Sun"], c: 0, e: "Snow = Nieve." },
    { t: "How do you say 'Viento' in English?", o: ["Wind", "Rain", "Snow", "Sun"], c: 0, e: "Wind = Viento." },
    { t: "How do you say 'Sol' in English?", o: ["Sun", "Moon", "Star", "Cloud"], c: 0, e: "Sun = Sol." },
    { t: "How do you say 'Nube' in English?", o: ["Cloud", "Sun", "Moon", "Rain"], c: 0, e: "Cloud = Nube." },
    { t: "How do you say 'Tormenta' in English?", o: ["Storm", "Rain", "Wind", "Snow"], c: 0, e: "Storm = Tormenta." },
    { t: "How do you say 'Trueno' in English?", o: ["Thunder", "Lightning", "Rain", "Wind"], c: 0, e: "Thunder = Trueno." },
    { t: "How do you say 'Relámpago' in English?", o: ["Lightning", "Thunder", "Rain", "Wind"], c: 0, e: "Lightning = Relampago." },
    { t: "How do you say 'Calor' in English?", o: ["Hot", "Cold", "Warm", "Cool"], c: 0, e: "Hot = Calor." },
    { t: "How do you say 'Frio' in English?", o: ["Cold", "Hot", "Warm", "Cool"], c: 0, e: "Cold = Frio." },
    { t: "How do you say 'Templado' in English?", o: ["Warm", "Hot", "Cold", "Cool"], c: 0, e: "Warm = Templado." },
    { t: "How do you say 'Fresco' in English?", o: ["Cool", "Hot", "Cold", "Warm"], c: 0, e: "Cool = Fresco." },
    { t: "How do you say 'Lluvioso' in English?", o: ["Rainy", "Sunny", "Cloudy", "Windy"], c: 0, e: "Rainy = Lluvioso." },
    { t: "How do you say 'Soleado' in English?", o: ["Sunny", "Rainy", "Cloudy", "Windy"], c: 0, e: "Sunny = Soleado." },
    { t: "How do you say 'Nublado' in English?", o: ["Cloudy", "Sunny", "Rainy", "Windy"], c: 0, e: "Cloudy = Nublado." },
    { t: "How do you say 'Ventoso' in English?", o: ["Windy", "Sunny", "Rainy", "Cloudy"], c: 0, e: "Windy = Ventoso." },
    { t: "How do you say 'Neblina' in English?", o: ["Fog", "Mist", "Cloud", "Smoke"], c: 0, e: "Fog = Neblina." },
    { t: "How do you say 'Granizo' in English?", o: ["Hail", "Snow", "Rain", "Ice"], c: 0, e: "Hail = Granizo." },
    { t: "How do you say 'Arcoíris' in English?", o: ["Rainbow", "Cloud", "Sun", "Rain"], c: 0, e: "Rainbow = Arcoiris." },
    { t: "What does 'What's the weather like?' mean?", o: ["Como esta el clima?", "Que tiempo hace?", "Que hora es?", "Donde estas?"], c: 0, e: "How is the weather? = Como esta el clima?" }
  ],
  "Food": [
    { t: "How do you say 'Pan' in English?", o: ["Bread", "Rice", "Pasta", "Meat"], c: 0, e: "Bread = Pan." },
    { t: "How do you say 'Arroz' in English?", o: ["Rice", "Bread", "Pasta", "Meat"], c: 0, e: "Rice = Arroz." },
    { t: "How do you say 'Leche' in English?", o: ["Milk", "Water", "Juice", "Coffee"], c: 0, e: "Milk = Leche." },
    { t: "How do you say 'Agua' in English?", o: ["Water", "Milk", "Juice", "Coffee"], c: 0, e: "Water = Agua." },
    { t: "How do you say 'Fruta' in English?", o: ["Fruit", "Vegetable", "Meat", "Bread"], c: 0, e: "Fruit = Fruta." },
    { t: "How do you say 'Verdura' in English?", o: ["Vegetable", "Fruit", "Meat", "Bread"], c: 0, e: "Vegetable = Verdura." },
    { t: "How do you say 'Carne' in English?", o: ["Meat", "Fish", "Chicken", "Egg"], c: 0, e: "Meat = Carne." },
    { t: "How do you say 'Pollo' in English?", o: ["Chicken", "Meat", "Fish", "Egg"], c: 0, e: "Chicken = Pollo." },
    { t: "How do you say 'Huevo' in English?", o: ["Egg", "Meat", "Fish", "Chicken"], c: 0, e: "Egg = Huevo." },
    { t: "How do you say 'Queso' in English?", o: ["Cheese", "Butter", "Milk", "Yogurt"], c: 0, e: "Cheese = Queso." },
    { t: "How do you say 'Mantequilla' in English?", o: ["Butter", "Cheese", "Milk", "Yogurt"], c: 0, e: "Butter = Mantequilla." },
    { t: "How do you say 'Cafe' in English?", o: ["Coffee", "Tea", "Juice", "Milk"], c: 0, e: "Coffee = Cafe." },
    { t: "How do you say 'Té' in English?", o: ["Tea", "Coffee", "Juice", "Milk"], c: 0, e: "Tea = Te." },
    { t: "How do you say 'Jugo' in English?", o: ["Juice", "Water", "Milk", "Coffee"], c: 0, e: "Juice = Jugo." },
    { t: "How do you say 'Manzana' in English?", o: ["Apple", "Banana", "Orange", "Grape"], c: 0, e: "Apple = Manzana." },
    { t: "How do you say 'Platano' in English?", o: ["Banana", "Apple", "Orange", "Grape"], c: 0, e: "Banana = Platano." },
    { t: "How do you say 'Naranja' in English?", o: ["Orange", "Apple", "Banana", "Grape"], c: 0, e: "Orange = Naranja." },
    { t: "How do you say 'Uva' in English?", o: ["Grape", "Apple", "Banana", "Orange"], c: 0, e: "Grape = Uva." },
    { t: "How do you say 'Papa' in English?", o: ["Potato", "Tomato", "Onion", "Carrot"], c: 0, e: "Potato = Papa." },
    { t: "How do you say 'Tomate' in English?", o: ["Tomato", "Potato", "Onion", "Carrot"], c: 0, e: "Tomato = Tomate." }
  ]
};

function gen(t) {
  const questions = bank[t] || bank["Greetings"];
  const bq = questions[rand(0, questions.length - 1)];
  return q("Ingles", bq.t, bq.o, bq.c, bq.e);
}

function makeQuestions() {
  const t = document.getElementById("topic").value;
  const arr = [];
  for (let i = 0; i < 2000; i++) {
    const type = t === "all" ? topics[rand(0, topics.length - 1)] : t;
    arr.push(gen(type));
  }
  return arr;
}
